### ISSUE TITLE
Could not save lang.yml 

### ISSUE THREAD

**Issue by The-Repo-Club** [Falyrion/AdvancedArmorStands#3]
[00:21:27 WARN]: [AdvancedArmorStands] Could not save lang.yml to plugins/AdvancedArmorStands/resources/lang.yml because lang.yml already exists.

**Comment by Falyrion** [comment]
You can ignore this error it's nothing important. But that you for reporting it, i will investigate further. Also make sure you are using the most recent version of the plugin (in console it prints out "v.1.17.4.0 for bukkit 1.17+") and the most recent version of bukkit/ spigot/ paper/ or whatever you use of that.

If the error still keeps appearing, delete the whole folder "AdvancedArmorStands" in your "plugins"-folder and restart the server. That should fix it.
