### ISSUE TITLE
DOESNT WORK

### ISSUE THREAD

**Issue by kurkinsnetwork** [Falyrion/AdvancedArmorStands#7]
hi dude ı found error pls fix it https://prnt.sc/2583hv3

**Comment by MajdT51** [comment]
> hi dude ı found error pls fix it https://prnt.sc/2583hv3

can you add more information, like which minecraft version are you using ? which java version? when does this error appear ?

**Comment by Falyrion** [comment]
Hey, sorry but the website you posted is not providing any information. You can copy and paste your error directly here.
