### ISSUE TITLE
allow claiming of armor stands

### ISSUE THREAD

**Issue by cardcraft** [Falyrion/AdvancedArmorStands#8]
maybe allow the claiming of certain armor stands so that other players cant mess with them. only the person who made it can.

also maybe they can add other people to allow to edit their armor stands

**Comment by Falyrion** [comment]
Thank you for your feedback. But there are tons of permissions plugins that allow you to do that. My plugin is purely for modifying armor stands. To protect armor stands please use a permissions plugin or anti-griefing plugin.
